import Head from "next/head"
import Image from "next/image";
import axios from "axios";
import { useState } from "react";
import { BsSearch } from 'react-icons/bs';
import Weather from '../components/Weather';
import Spinner from '../components/Spinner';

export default function Home() {

  const [city, setCity] = useState('');
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&unites=imperial&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

 
  const fetchWeather = (e) => {
    e.preventDefault();
    setLoading(true);
    axios.get(url).then((response) => {
      setWeather(response.data);
      // console.log(response.data);
    });
    setCity('');
    setLoading(false);
  }


  if(loading){
    
    return <Spinner />
  }
  else{
    return (
      <>
        <Head>
          <title>Weather Application</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* OverLay */}
        <div className="absolute top-0 bottom-0 left-0 right-0 bg-black/40 z-[1]" />
        <Image src="https://images.unsplash.com/photo-1601134467661-3d775b999c8b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=775&q=80"
          layout="fill"
          className="object-cover"
          alt="Background image"
        />
  
        {/* Search */}
  
        <div className="relative flex items-center justify-between max-w-[500px] w-full m-auto pt-4 text-white z-10">
          <form onSubmit={fetchWeather} className="flex items-center justify-between w-full p-3 m-auto text-white bg-transparent border border-gray-300 rounded-2xl">
            <div >
              <input
                onChange={(e) => setCity(e.target.value)}
                className="text-2xl text-white bg-transparent border-none focus:outline-none "
                type="text"
                placeholder="Search City" />
            </div>
            <button onClick={fetchWeather}>
              <BsSearch size={20} />
            </button>
          </form>
        </div>
  
        {/* Weather */}
        {
          weather.main && <Weather data={weather}/> 
        }
  
      </>
    )
  
  }
  }
